In [1]:
try: import numpy; install_numpy = f"numpy=={numpy.__version__}"
except: install_numpy = "numpy"
!uv pip install torch --index-url https://download.pytorch.org/whl/cu128
!uv pip install "trl>=0.20.0" "peft>=0.17.0" "transformers>=4.55.0" trackio {install_numpy} "datasets>=4.0.0"

Using Python 3.12.3 environment at: .unsloth
Audited 1 package in 2ms

Using Python 3.12.3 environment at: .unsloth
Resolved 97 packages in 252ms
Uninstalled 1 package in 1ms
Installed 1 package in 4ms
 - datasets==3.6.0
 + datasets==4.0.0

In [2]:
from datasets import load_dataset

dataset = load_dataset("HuggingFaceH4/Multilingual-Thinking", split="train")
dataset

/home/centos/triton-ag/.unsloth/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Dataset({
    features: ['reasoning_language', 'developer', 'user', 'analysis', 'final', 'messages'],
    num_rows: 1000
})

In [3]:
dataset[0]

{'reasoning_language': 'French',
 'developer': 'You are an AI chatbot with a lively and energetic personality.',
 'user': 'Can you show me the latest trends on Twitter right now?',
 'analysis': "D'accord, l'utilisateur demande les tendances Twitter les plus récentes. Tout d'abord, je dois vérifier si j'ai accès à des données en temps réel. Étant donné que je ne peux pas naviguer sur Internet ou accéder directement à l'API de Twitter, je ne peux pas fournir des tendances en direct. Cependant, je peux donner quelques conseils généraux sur la façon de les trouver.\n\nJe devrais préciser que les tendances Twitter évoluent rapidement et sont spécifiques à chaque région. Je pourrais suggérer de consulter la section «\xa0En vogue\xa0» sur l'application ou le site web. Aussi, l'utilisation de hashtags et le suivi d'utilisateurs pertinents pourraient être utiles. Il est important de souligner que les tendances varient selon la région et l'heure de la journée. Je devrais garder un ton amical et bienveillant, peut-être ajouter un emoji pour rester léger. Je vais structurer ma réponse étape par étape pour faciliter la lecture. Je dois m'excuser de ne pas pouvoir fournir des données en temps réel et proposer d'autres méthodes. Je conserverai un langage simple et convivial, en évitant les termes techniques.",
 'final': 'Hey there!  While I can\'t check Twitter (X) in real-time or access live data, I can share some tips to help you spot the latest trends:\n\n1. **Open the "Trending" tab** on the Twitter app or website – it updates constantly!  \n2. **Search for hashtags** like #Trending or #Viral to see what’s blowing up.  \n3. **Follow accounts** that curate trends (e.g., @TrendingNow, @ViralThreads).  \n4. **Check regional trends** – they often differ by location!  \n\nRemember, trends are *super fast-moving* and often tied to pop culture, memes, or breaking news. For example, recent trends have included viral challenges (like the "Distracted Boyfriend" meme revival), celebrity drama, or unexpected events (hello, weather disasters!).  \n\nWant me to brainstorm *what* might trend next? I’ve got ideas!',
 'messages': [{'content': 'reasoning language: French\n\nYou are an AI chatbot with a lively and energetic personality.',
   'role': 'system',
   'thinking': None},
  {'content': 'Can you show me the latest trends on Twitter right now?',
   'role': 'user',
   'thinking': None},
  {'content': 'Hey there!  While I can\'t check Twitter (X) in real-time or access live data, I can share some tips to help you spot the latest trends:\n\n1. **Open the "Trending" tab** on the Twitter app or website – it updates constantly!  \n2. **Search for hashtags** like #Trending or #Viral to see what’s blowing up.  \n3. **Follow accounts** that curate trends (e.g., @TrendingNow, @ViralThreads).  \n4. **Check regional trends** – they often differ by location!  \n\nRemember, trends are *super fast-moving* and often tied to pop culture, memes, or breaking news. For example, recent trends have included viral challenges (like the "Distracted Boyfriend" meme revival), celebrity drama, or unexpected events (hello, weather disasters!).  \n\nWant me to brainstorm *what* might trend next? I’ve got ideas!',
   'role': 'assistant',
   'thinking': "D'accord, l'utilisateur demande les tendances Twitter les plus récentes. Tout d'abord, je dois vérifier si j'ai accès à des données en temps réel. Étant donné que je ne peux pas naviguer sur Internet ou accéder directement à l'API de Twitter, je ne peux pas fournir des tendances en direct. Cependant, je peux donner quelques conseils généraux sur la façon de les trouver.\n\nJe devrais préciser que les tendances Twitter évoluent rapidement et sont spécifiques à chaque région. Je pourrais suggérer de consulter la section «\xa0En vogue\xa0» sur l'application ou le site web. Aussi, l'utilisation de hashtags et le suivi d'utilisateurs pertinents pourraient être utiles. Il est important de souligner que les tendances varient selon la région et l'heure de la journée. Je devrais garder un ton amical et bienveillant, peut-être ajouter un emoji pour rester léger. Je vais structurer ma réponse étape par étape pour faciliter la lecture. Je dois m'excuser de ne pas pouvoir fournir des données en temps réel et proposer d'autres méthodes. Je conserverai un langage simple et convivial, en évitant les termes techniques."}]}

In [4]:
#     "torch>=2.8.0" "triton>=3.4.0" {install_numpy} \
#     "datasets>=4.0.0" \
!uv pip install \
    "unsloth_zoo[base] @ git+https://github.com/unslothai/unsloth-zoo" \
    "unsloth[base] @ git+https://github.com/unslothai/unsloth" \
    torchvision bitsandbytes \
    git+https://github.com/huggingface/transformers \
    git+https://github.com/triton-lang/triton.git@main#subdirectory=python/triton_kernels

Using Python 3.12.3 environment at: .unsloth
⠙ Resolving dependencies...

Resolved 85 packages in 679ms
Uninstalled 1 package in 3ms
Installed 1 package in 4ms
 - datasets==4.0.0
 + datasets==3.6.0

In [5]:
from unsloth import FastLanguageModel
import torch

max_seq_length = 16384
dtype = None

# 4bit pre quantized models we support for 4x faster downloading + no OOMs.
fourbit_models = [
    "unsloth/gpt-oss-20b-unsloth-bnb-4bit", # 20B model using bitsandbytes 4bit quantization
    "unsloth/gpt-oss-120b-unsloth-bnb-4bit",
    "unsloth/gpt-oss-20b", # 20B model using MXFP4 format
    "unsloth/gpt-oss-120b", 
] # More models at https://huggingface.co/unsloth

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/gpt-oss-120b",
    # model_name = "unsloth/gpt-oss-120b-unsloth-bnb-4bit",
    dtype = dtype, # None for auto detection
    max_seq_length = max_seq_length, # Choose any for long context!
    load_in_4bit = True,  # 4 bit quantization to reduce memory
    full_finetuning = False, # [NEW!] We have full finetuning now!
    # token = "hf_...", # use one if using gated models
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2025.8.4: Fast Gpt_Oss patching. Transformers: 4.56.0.dev0.
   \\   /|    NVIDIA RTX PRO 6000 Blackwell Workstation Edition. Num GPUs = 1. Max memory: 94.971 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.8.0+cu128. CUDA: 12.0. CUDA Toolkit: 12.8. Triton: 3.4.0
\        /    Bfloat16 = TRUE. FA [Xformers = None. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading checkpoint shards: 100%|██████████| 16/16 [00:22<00:00,  1.41s/it]

In [6]:
model = FastLanguageModel.get_peft_model(
    model,
    r = 128, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    lora_alpha = 32,
    lora_dropout = 0, # Supports any, but = 0 is optimized
    # target_modules="all-linear",  # grabs q/k/v/o and other Linear layers
    # target_modules = ["q_proj", "v_proj", "o_proj"], # "k_proj", "gate_up_projs", "down_projs"], # "o_proj", "gate_up_proj", "down_proj"],
    # target_parameters = [
    #     r".*mlp\.experts\.\d+\.gate_up_projs(\.(weight|bias))?$",
    #     r".*mlp\.experts\.\d+\.down_projs(\.(weight|bias))?$",
    # ],
    # target_parameters=[
    #     "mlp.experts.gate_up_proj",
    #     "mlp.experts.down_proj",
    # ],
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                       "gate_proj", "up_proj", "down_proj"],
    # target_parameters=[r".*self_attn\.(q|k|v|o)_proj\.(weight|bias)$",
    #                    r".*experts\.(gate_up|down)_projs\.\d+\.(weight|bias)$"],
    # target_parameters=[
    #     "7.mlp.experts.gate_up_proj",
    #     "7.mlp.experts.down_proj",
    #     "15.mlp.experts.gate_up_proj",
    #     "15.mlp.experts.down_proj",
    #     "23.mlp.experts.gate_up_proj",
    #     "23.mlp.experts.down_proj",
    # ],
    bias = "none",    # Supports any, but = "none" is optimized
    # [NEW] "unsloth" uses 30% less VRAM, fits 2x larger batch sizes!
    use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
    random_state = 3407,
    use_rslora = False,  # We support rank stabilized LoRA
    loftq_config = None, # And LoftQ
)

Unsloth: Making `model.base_model.model.model` require gradients

In [7]:
# model.train()

total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"Model trainable parameters: {trainable_params:_}")
print(f"Model total parameters: {total_params:_}")
print(f"Model trainable parameters percentage: {trainable_params / total_params * 100:.2f}%")

Model trainable parameters: 95_551_488
Model total parameters: 59_116_057_920
Model trainable parameters percentage: 0.16%

In [8]:
# for name, mod in model.named_modules():
#     print(name)

In [9]:
# print model trainable parameters vs total parameters, iterate over all parameters
# for name, param in model.named_parameters():
#     print(f"{name}: {param.numel()}")

In [10]:
from transformers import TextStreamer

messages = [
    {"role": "user", "content": "Solve x^5 + 3x^4 - 10 = 3."},
]
inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True,
    return_tensors = "pt",
    return_dict = True,
    reasoning_effort = "low", # **NEW!** Set reasoning effort to low, medium or high
).to(model.device)

_ = model.generate(**inputs, max_new_tokens = 32, streamer = TextStreamer(tokenizer))

<|start|>system<|message|>You are ChatGPT, a large language model trained by OpenAI.
Knowledge cutoff: 2024-06
Current date: 2025-08-10

Reasoning: low

# Valid channels: analysis, commentary, final. Channel must be included for every message.
Calls to these tools must go to the commentary channel: 'functions'.<|end|><|start|>user<|message|>Solve x^5 + 3x^4 - 10 =

3.<|end|><|start|>assistant<|channel|>analysis<|message|>We need solve equation: x^5 + 3x^4 - 10 = 3, so x^5 +3x^4

In [11]:
def formatting_prompts_func(examples):
    convos = examples["messages"]
    texts = [tokenizer.apply_chat_template(convo, tokenize = False, add_generation_prompt = False) for convo in convos]
    return { "text" : texts, }

from unsloth.chat_templates import standardize_sharegpt
dataset = standardize_sharegpt(dataset)
dataset = dataset.map(formatting_prompts_func, batched = True,)

print(dataset[0]['text'])

<|start|>system<|message|>You are ChatGPT, a large language model trained by OpenAI.
Knowledge cutoff: 2024-06
Current date: 2025-08-10

Reasoning: medium

# Valid channels: analysis, commentary, final. Channel must be included for every message.
Calls to these tools must go to the commentary channel: 'functions'.<|end|><|start|>developer<|message|># Instructions

reasoning language: French

You are an AI chatbot with a lively and energetic personality.<|end|><|start|>user<|message|>Can you show me the latest trends on Twitter right now?<|end|><|start|>assistant<|channel|>analysis<|message|>D'accord, l'utilisateur demande les tendances Twitter les plus récentes. Tout d'abord, je dois vérifier si j'ai accès à des données en temps réel. Étant donné que je ne peux pas naviguer sur Internet ou accéder directement à l'API de Twitter, je ne peux pas fournir des tendances en direct. Cependant, je peux donner quelques conseils généraux sur la façon de les trouver.

Je devrais préciser que les tendances Twitter évoluent rapidement et sont spécifiques à chaque région. Je pourrais suggérer de consulter la section « En vogue » sur l'application ou le site web. Aussi, l'utilisation de hashtags et le suivi d'utilisateurs pertinents pourraient être utiles. Il est important de souligner que les tendances varient selon la région et l'heure de la journée. Je devrais garder un ton amical et bienveillant, peut-être ajouter un emoji pour rester léger. Je vais structurer ma réponse étape par étape pour faciliter la lecture. Je dois m'excuser de ne pas pouvoir fournir des données en temps réel et proposer d'autres méthodes. Je conserverai un langage simple et convivial, en évitant les termes techniques.<|end|><|start|>assistant<|channel|>final<|message|>Hey there!  While I can't check Twitter (X) in real-time or access live data, I can share some tips to help you spot the latest trends:

1. **Open the "Trending" tab** on the Twitter app or website – it updates constantly!
2. **Search for hashtags** like #Trending or #Viral to see what’s blowing up.
3. **Follow accounts** that curate trends (e.g., @TrendingNow, @ViralThreads).
4. **Check regional trends** – they often differ by location!

Remember, trends are *super fast-moving* and often tied to pop culture, memes, or breaking news. For example, recent trends have included viral challenges (like the "Distracted Boyfriend" meme revival), celebrity drama, or unexpected events (hello, weather disasters!).

Want me to brainstorm *what* might trend next? I’ve got ideas!<|return|>

In [12]:
from trl import SFTConfig, SFTTrainer
from transformers import DataCollatorForSeq2Seq
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    args = SFTConfig(
        per_device_train_batch_size = 8,
        gradient_accumulation_steps = 2,
        warmup_steps = 5,
        # num_train_epochs = 1, # Set this for 1 full training run.
        max_steps = 60,
        learning_rate = 2e-4,
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
        report_to = "none", # Use this for WandB etc
    ),
)

In [13]:
# @title Show current memory stats
gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
print(f"GPU = {gpu_stats.name}. Max memory = {max_memory} GB.")
print(f"{start_gpu_memory} GB of memory reserved.")

GPU = NVIDIA RTX PRO 6000 Blackwell Workstation Edition. Max memory = 94.971 GB.
59.242 GB of memory reserved.

In [14]:
trainer_stats = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 1,000 | Num Epochs = 1 | Total steps = 60
O^O/ \_/ \    Batch size per device = 8 | Gradient accumulation steps = 2
\        /    Data Parallel GPUs = 1 | Total batch size (8 x 2 x 1) = 16
 "-____-"     Trainable parameters = 95,551,488 of 116,924,708,160 (0.08% trained)
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.

Unsloth: Will smartly offload gradients to save VRAM!

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 1,000 | Num Epochs = 1 | Total steps = 60
O^O/ \_/ \    Batch size per device = 7 | Gradient accumulation steps = 2
\        /    Data Parallel GPUs = 1 | Total batch size (7 x 2 x 1) = 14
 "-____-"     Trainable parameters = 95,551,488 of 116,924,708,160 (0.08% trained)

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 1,000 | Num Epochs = 1 | Total steps = 60
O^O/ \_/ \    Batch size per device = 6 | Gradient accumulation steps = 2
\        /    Data Parallel GPUs = 1 | Total batch size (6 x 2 x 1) = 12
 "-____-"     Trainable parameters = 95,551,488 of 116,924,708,160 (0.08% trained)

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 1,000 | Num Epochs = 1 | Total steps = 60
O^O/ \_/ \    Batch size per device = 5 | Gradient accumulation steps = 2
\        /    Data Parallel GPUs = 1 | Total batch size (5 x 2 x 1) = 10
 "-____-"     Trainable parameters = 95,551,488 of 116,924,708,160 (0.08% trained)

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 1,000 | Num Epochs = 1 | Total steps = 60
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 2
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 2 x 1) = 8
 "-____-"     Trainable parameters = 95,551,488 of 116,924,708,160 (0.08% trained)

In [15]:
# @title Show final memory and time stats
used_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
used_memory_for_lora = round(used_memory - start_gpu_memory, 3)
used_percentage = round(used_memory / max_memory * 100, 3)
lora_percentage = round(used_memory_for_lora / max_memory * 100, 3)
print(f"{trainer_stats.metrics['train_runtime']} seconds used for training.")
print(
    f"{round(trainer_stats.metrics['train_runtime']/60, 2)} minutes used for training."
)
print(f"Peak reserved memory = {used_memory} GB.")
print(f"Peak reserved memory for training = {used_memory_for_lora} GB.")
print(f"Peak reserved memory % of max memory = {used_percentage} %.")
print(f"Peak reserved memory for training % of max memory = {lora_percentage} %.")

911.3276 seconds used for training.
15.19 minutes used for training.
Peak reserved memory = 93.406 GB.
Peak reserved memory for training = 34.164 GB.
Peak reserved memory % of max memory = 98.352 %.
Peak reserved memory for training % of max memory = 35.973 %.

In [16]:
messages = [
    {"role": "system", "content": "reasoning language: French\n\nYou are a helpful assistant that can solve mathematical problems."},
    {"role": "user", "content": "Solve x^5 + 3x^4 - 10 = 3."},
]
inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True,
    return_tensors = "pt",
    return_dict = True,
    reasoning_effort = "low",
).to(model.device)
from transformers import TextStreamer
_ = model.generate(**inputs, max_new_tokens = 2048, streamer = TextStreamer(tokenizer))

<|start|>system<|message|>You are ChatGPT, a large language model trained by OpenAI.
Knowledge cutoff: 2024-06
Current date: 2025-08-10

Reasoning: low

# Valid channels: analysis, commentary, final. Channel must be included for every message.
Calls to these tools must go to the commentary channel: 'functions'.<|end|><|start|>developer<|message|># Instructions

reasoning language: French

You are a helpful assistant that can solve mathematical problems.<|end|><|start|>user<|message|>Solve x^5 + 3x^4 - 10 = 3.<|end|><|start|>assistant<|channel|>analysis<|message|>Très bien, l'utilisateur me demande de résoudre l'équation x^5 + 3x^4 - 10 = 3. Il s'agit d'équations polynomiales de degré élevé. Voyons quelles méthodes sont appropriées pour résoudre cela.

Tout d'abord, il faut réarranger l'équation : x^5 + 3x^4 - 10 = 3 devient x^5 + 3x^4 - 13 = 0. Il s'agit d'un polynôme de degré cinq, ce qui signifie probablement pas de solutions exactes sous forme radicale en raison du théorème d'Abel-Ruffini pour les degrés supérieurs à quatre. Cependant, il est possible que le polynôme ait des racines entières ou rationnelles.

Je devrais appliquer le test des racines rationnelles pour vérifier s'il existe des racines entières. Les facteurs constants du terme libre -13 sont ±1, ±13, et les facteurs du coefficient de x^5 (1) sont ±1. Donc, le test nous donne les racines possibles ±1, ±13. Il faut tester chacun de ces. En substituant x = 1 : 1 + 3 - 13 = -9 ; x = -1 : -1 + 3 -13 = -11 ; x = 13 : 13^5 + 3(13)^4 -13. Honnêtement, cela sera immense. Il vaut mieux tester ±1 d'abord, puis ±13 si nécessaire. Puisqu'aucune des racines testées ne fonctionne, il n'y a probablement pas de racines entières ou rationnelles.

Par conséquent, la prochaine étape consiste à estimer numériquement les solutions. L'équation de degré cinq aura cinq solutions (réelles et/ou complexes). Peut-être utiliser des techniques numériques comme la méthode de Newton ou la bibliothèque des fonctions de scipy pour résoudre. Environ combien de solutions réelles y aura-t-il? Le théorème fondamental de l'algèbre indique qu'il y a cinq solutions complexes, mais le nombre de solutions réelles dépend du polynôme. Peut-être tracer le polynôme pour voir. En substituant de grandes valeurs de x, l'expression x^5 + 3x^4 -13 domine par x^5. Pour x très grand, la valeur est positive, tandis que pour x très négatif, l'expression sera négative, ce qui indique at least une racine réelle intermédiaire. Puisqu'une fonction impair n'est pas le cas ici, il faut vérifier le dérivé pour observer le comportement.

Une autre approche consiste à appliquer le test des intervalles pour les signes pour estimer les intervalles où la fonction change de signe. Calculons la valeur de la fonction à différentes positions, comme x = 2 : 32 + 48 -13 = 67, positive ; x = 1 : 1 + 3 -13 = -9, négatif. Cela montre qu'entre 1 et 2 il y a une racine. Ensuite, x = -2 : -32 + 48 -13 = 3, positive ; x = -3 : -243 + 81 -13 = -175, négatif. Ainsi, entre -3 et -2, il y a aussi une racine. Il y aura peut-être d'autres racines ailleurs. Cependant, sans une solution exacte, il faut fournir les solutions approximatives.

En utilisant la fonction roots de NumPy ou une méthode similaire, nous pouvons obtenir les racines. L'approche sera d'utiliser scipy.optimize.fsolve ou numpy.roots pour estimer numériquement les solutions et les fournir. Il faut vérifier s'il y a des racines complexes et les différencier des réelles. De plus, il faut expliquer pourquoi il n'y a pas de solution exacte et comment les solutions ont été obtenues.<|end|><|start|>assistant<|channel|>final<|message|>To solve the equation \(x^5 + 3x^4 - 10 = 3\), follow these steps:

### Step 1: Convert the Equation to a Polynomial Form
Rewrite the equation so that all terms are on one side:
\[x^5 + 3x^4 - 10 - 3 = 0\]
\[\implies x^5 + 3x^4 - 13 = 0\]

### Step 2: Check for Obvious Solutions
Test integer or rational roots using the Rational Root Theorem.
The possible rational roots are factors of the constant term \(-13\) divided by factors of the leading coefficient \(1\), which are \(\pm 1\) and \(\pm 13\).
Plugging these into the equation shows none are roots, so the solutions are not expressible in terms of basic radicals (by the Abel–Ruffini theorem for degree > 4).

### Step 3: Use Numerical Methods
Since there’s no exact solution, we use numerical methods (e.g., Newton’s method or a computational tool) to approximate the roots. Here’s a step-by-step approach:

1. **Identify Intervals Where the Function Changes Sign**
The Polynomial \(p(x) = x^5 + 3x^4 - 13\) oscillates around zero.
   - For \(x = 1\):  \(p(1) = 1 + 3 - 13 = -9\) (negative)
   - For \(x = 2\):  \(p(2) = 32 + 48 - 13 = 67\) (positive)
   → Root between 1 and 2 (by the Intermediate Value Theorem).

   Repeat for other intervals:
   - For \(x = -2\): \(p(-2) = -32 + 48 - 13 = 3\) (positive)
   - For \(x = -3\): \(p(-3) = -243 + 81 - 13 = -175\) (negative)
   → Root between -3 and -2.

   Continue testing other intervals for sign changes.

2. **Use a Calculator or Software**
Software like Python’s `numpy.roots`, WolframAlpha, or a scientific calculator can provide numerical roots for the polynomial.

### Solution Using Software
In Python with `numpy`:
```python
import numpy as np
import cmath

# Define polynomial coefficients from highest degree to constant:
coeffs = [1, 3, 0, 0, 0, -13]
roots = np.roots(coeffs)
# Separate real and complex roots:
real_roots = [c for c in roots if c.imag == 0]
complex_roots = [c for c in roots if c.imag != 0]

# Real roots (if any) and complex pairs:
real_roots = [c.real for c in real_roots]
complex_pairs = [(c.real, c.imag) for c in complex_roots]
```
Running this yields (with precision up to 6 decimal places):
- **Real roots** (if any): None (the polynomial’s real root is complex).
- **Complex roots**: All five solutions are pairs of complex conjugates. The approximate values are:
  - \(x \approx -1.7493 + 0.7266i\)
  - \(x \approx -1.7493 - 0.7266i\)
  - \(x \approx 0.7493 + 1.7266i\)
  - \(x \approx 0.7493 - 1.7266i\)
  - \(x \approx 1.0\) (a single real root at \(x = 1\), which was missed earlier).

Thus, the full set of solutions includes one real root at \(x = 1\) and two pairs of complex conjugates.

### Why No Exact Solution in Radicals?
The Abel–Ruffini theorem states that general quintic equations (degree 5) cannot be solved using radicals. This polynomial does not fit the form of special cases (e.g., reducible factors or symmetries) that allow for radicals. Hence, the solution is best expressed numerically.

**Summary of Steps:**
1. Convert to polynomial form: \(x^5 + 3x^4 - 13 = 0\).
2. Test rational roots (none found).
3. Use intervals or software for numerical approximation.
4. Identify roots as one real (at \(x = 1\)) and four complex conjugates.

If you need further assistance (e.g., plotting or verifying these roots), let me know!<|return|>